# -*- coding: utf-8 -*-
"""Untitled14(5).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HaMMWhs122sD8dul_TJj6ed6Vyf63LiL
"""

import os
from pathlib import Path
import shutil
import random
import torch
import torch.nn as nn
import torchinfo
from torchinfo import summary
from torchvision import datasets, models, transforms

import PIL
from PIL import Image

import torch.utils
import torch.optim as optim
from torch.utils.data import DataLoader, random_split

downloadedfile = Path(r"C:\Users\Jelil\Downloads\archive (4).zip")
base_dir = Path(r"C:\Users\Jelil\Desktop\New folder (12)")

import zipfile
with zipfile.ZipFile(downloadedfile, "r") as f:
    f.extractall(base_dir)

dataset_path = Path(r"C:\Users\Jelil\Desktop\New folder (12)\Pistachio_Image_Dataset\New folder (2)")
dataset_path.mkdir(parents=True, exist_ok=True)

Kirmizi_dir = dataset_path / "Kirmizi_Pistachio"
Kirmizi_dir.mkdir(parents=True, exist_ok=True)

Siirt_dir = dataset_path / "Siirt_Pistachio"
Siirt_dir.mkdir(parents=True, exist_ok=True)

for dirss in base_dir.iterdir():
    for dirs in dirss.iterdir():
        if dirs.stem != "Pistachio_Image_Dataset":
            continue
        for paths in dirs.iterdir():
            if paths.suffix == ".txt":
                continue

            for classs in paths.iterdir():
                if classs.suffix.lower() != ".jpg":
                    continue

                # Validate image before copying
                try:
                    Image.open(classs).verify()
                except Exception as e:
                    print(f"Skipping bad image: {classs} ({e})")
                    continue


                if classs.stem.split(" ")[0] == "kirmizi":
                    dst = Kirmizi_dir / f"{classs.name}"
                    shutil.copy(classs, dst)

                else:
                    dst = Siirt_dir / f"{classs.name}"
                    shutil.copy(classs, dst)

height = 224
width = 224

transform = transforms.Compose([
    transforms.Resize((height, width)),
    transforms.ToTensor()
    ])

datasetz = datasets.ImageFolder(root = dataset_path, transform = transform)

from collections import Counter
counts = Counter(i for _, i in datasetz)
class_distribution = {k: counts[v] for k,v in datasetz.class_to_idx.items()}
print(class_distribution)

from torch.utils.data import Subset
from collections import defaultdict
import random
classindex = defaultdict(list)

for idx,(_,label) in enumerate(datasetz):
    classindex[label].append(idx)

subset_idx = []
n_sample = 800

for classlabel, id_list in classindex.items():

    k = min(len(id_list), n_sample)   # safe sample size
    sample_idx = random.sample(id_list, k)
    subset_idx.extend(sample_idx)

final_dataset = Subset(datasetz, subset_idx)

count = Counter([l for _, l in final_dataset])
print(count)

from collections import defaultdict
from torch.utils.data import Subset
import random

classindex = defaultdict(list)

# Build class → indices
for idx, (_, label) in enumerate(datasetz):
    classindex[label].append(idx)

subset_idx = []
n_sample = 900

for classlabel, id_list in classindex.items():
    k = min(len(id_list), n_sample)   # safe sample size
    sample_idx = random.sample(id_list, k)
    subset_idx.extend(sample_idx)

final_dataset = Subset(datasetz, subset_idx)

len(final_dataset)

from collections import Counter
counts = Counter(i for _, i in final_dataset)
class_distribution = {k: counts[v] for k,v in final_dataset.class_to_idx.items()}
print(class_distribution)

img, label = datasetz[0]
print(type(img), img.shape)
print("Label index:", label)
print("Class name:", datasetz.classes[label])

from collections import Counter
from tqdm.notebook import tqdm

batch_size = 32
dataset_loader = DataLoader(datasetz, batch_size = 32, shuffle= True)

# Get one batch

first_batch = next(iter(dataset_loader))
print(f"Shape of one batch: {first_batch[0].shape}")

def get_mean_std(loader):

    channels_sum, channels_squared_sum, num_batches = 0, 0, 0

    for data, _ in tqdm(loader):
        channels_sum += torch.mean(data, dim=[0, 2, 3])
        channels_squared_sum += torch.mean(data**2, dim=[0, 2, 3])
        num_batches += 1

        mean = channels_sum/num_batches

        std = (channels_squared_sum/num_batches - mean**2)**0.5
        return mean, std

mean, std = get_mean_std(dataset_loader)
print(f"Mean: {mean}")
print(f"Standard deviation: {std}")

height = 224
width = 224

transformNorm = transforms.Compose([
    transforms.Resize((height, width)),
    transforms.ToTensor(),
    transforms.Normalize(mean = mean, std= std)
    ])

dataset = datasets.ImageFolder(root = dataset_path, transform = transformNorm)

classes = {v:k for k,v in (dataset.class_to_idx).items()}
print(classes)

img, label = dataset[0]
img.shape
print(label)

g = torch.Generator()
g.manual_seed(42)

train_datasets, val_dataset = random_split(dataset, [0.85, 0.15] , generator=g)

g = torch.Generator()
g.manual_seed(42)

train_dataset, test_dataset = random_split(train_datasets, [0.85, 0.15] , generator=g)

def counterz(dataset):
    counts = Counter(i for _, i in dataset)
    class_distribution = {k: counts[v] for k,v in datasetz.class_to_idx.items()}
    return class_distribution

traincounts = counterz(train_dataset)
traincounts

testcounts = counterz(test_dataset)
testcounts

valcounts = counterz(val_dataset)
valcounts

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=True)
TestLoader = DataLoader(test_dataset, batch_size=32, shuffle=True)

import torchvision
from torchvision import models
import torchvision.models as models

model = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V2)
print(model)

model.fc

for params in model.parameters():
    params.requires_grad = False

torch.manual_seed(42)

in_features = model.fc.in_features

modified_last_layer = nn.Sequential()

dense_layer = nn.Linear(in_features, 256)
modified_last_layer.append(dense_layer)
relu = nn.ReLU()
modified_last_layer.append(relu)
modified_last_layer.append(nn.Dropout(p=0.5))
output_layer = nn.Linear(256, 2)
modified_last_layer.append(output_layer)

model.fc = modified_last_layer

print(model)

def train_epoch(modelu, optimizer, loss_fn, data_loader, device="cpu"):
    training_loss = 0.0
    modelu.train()

    for inputs, targets in tqdm(data_loader, desc="Training", leave=False):
        optimizer.zero_grad()
        inputs = inputs.to(device)
        targets = targets.to(device)
        output = modelu(inputs)
        loss = loss_fn(output, targets)
        loss.backward()
        optimizer.step()
        training_loss += loss.data.item() * inputs.size(0)
    return training_loss / len(data_loader.dataset)

def predict(modelu, data_loader, device="cpu"):
    all_probs = torch.tensor([]).to(device)
    modelu.eval()
    with torch.no_grad():
        for inputs, targets in tqdm(data_loader, desc="Predicting", leave=False):

            output = model(inputs)
            probs = torch.nn.functional.softmax(output, dim=1)
            all_probs = torch.cat((all_probs, probs), dim=0)
    return all_probs

def score(modelu, data_loader, loss_fn, device="cpu"):
    total_loss = 0
    total_correct = 0
    modelu.eval()
    with torch.no_grad():
        for inputs, targets in tqdm(data_loader, desc="Scoring", leave=False):
            inputs = inputs.to(device)
            output = modelu(inputs)
            targets = targets.to(device)
            loss = loss_fn(output, targets)
            total_loss += loss.data.item() * inputs.size(0)
            correct = torch.eq(torch.argmax(output, dim=1), targets)
            total_correct += torch.sum(correct).item()
    n_observations = data_loader.batch_size * len(data_loader)
    average_loss = total_loss / n_observations
    accuracy = total_correct / n_observations
    return average_loss, accuracy

def early_stopping(validation_loss, best_val_loss, counter):
    """Function that implements Early Stopping"""
    stop = False
    if validation_loss < best_val_loss:
        counter = 0
    else:
        counter += 1
    if counter >= 5: # our patience is 5 epochs
        stop = True
    return counter, stop

def checkpointing(validation_loss, best_val_loss, modelu, optimizer, save_path):
    """Function that implements Checkpointing"""
    if validation_loss < best_val_loss:
        torch.save(
        {
        "model_state_dict": modelu.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
        "loss": best_val_loss
        },
        save_path,
        )
    print(f"Checkpoint saved with validation loss {validation_loss:.4f}")

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = 0.001, weight_decay=0.0001)


optimizer2 = torch.optim.Adam(modelu.parameters(), lr = 0.002)

from torch.optim.lr_scheduler import StepLR
step_size = 4
# Multiplicative factor of learning rate decay
gamma = 0.2
# Initialize the learning rate scheduler
scheduler = StepLR(
    optimizer2,
    step_size=step_size,
    gamma=gamma,
    )

def train(
    modelu,
    optimizer2,
    loss_fn,
    train_loader,
    val_loader,
    epochs=20,
    device="cpu",
    scheduler=None,
    checkpoint_path=None,
    early_stopping=None,
):
    # Track metrics
    train_losses = []
    train_accuracies = []
    val_losses = []
    val_accuracies = []
    learning_rates = []

    best_val_loss = float("inf")
    early_stopping_counter = 0

    print("Model evaluation before start of training...")

    # Initial evaluation
    train_loss, train_accuracy = score(modelu, train_loader, loss_fn, device)
    train_losses.append(train_loss)
    train_accuracies.append(train_accuracy)

    validation_loss, validation_accuracy = score(modelu, val_loader, loss_fn, device)
    val_losses.append(validation_loss)
    val_accuracies.append(validation_accuracy)

    for epoch in range(1, epochs + 1):
        print("\n")
        print(f"Starting epoch {epoch}/{epochs}")

        # Train one epoch
        train_epoch(modelu, optimizer2, loss_fn, train_loader, device)

        # Evaluate training
        train_loss, train_accuracy = score(modelu, train_loader, loss_fn, device)
        train_losses.append(train_loss)
        train_accuracies.append(train_accuracy)

        # Evaluate validation
        validation_loss, validation_accuracy = score(modelu, val_loader, loss_fn, device)
        val_losses.append(validation_loss)
        val_accuracies.append(validation_accuracy)

        print(f"Epoch: {epoch}")
        print(f"Training loss: {train_loss:.4f}")
        print(f"Training accuracy: {train_accuracy*100:.4f}%")
        print(f"Validation loss: {validation_loss:.4f}")
        print(f"Validation accuracy: {validation_accuracy*100:.4f}%")

        # Log LR
        lr = optimizer.param_groups[0]["lr"]
        learning_rates.append(lr)

        if scheduler:
            scheduler.step()

        # Checkpointing
        if checkpoint_path:
            checkpointing(
                validation_loss, best_val_loss, modelu, optimizer, checkpoint_path
            )

        # Early stopping
        if early_stopping:
            early_stopping_counter, stop = early_stopping(
                validation_loss, best_val_loss, early_stopping_counter
            )
            if stop:
                print(f"Early stopping triggered after {epoch} epochs")
                break

        # Update best loss
        if validation_loss < best_val_loss:
            best_val_loss = validation_loss

    return (
        learning_rates,
        train_losses,
        val_losses,
        train_accuracies,
        val_accuracies,
        epoch,
    )

device = "cuda" if torch.cuda.is_available() else "cpu"

Path(r"C:\Users\Jelil\Desktop\New folder (12)\Pistachio_Image_Dataset\New folder (3)")

epochs_to_train = 50

checkpoint_path = Path(
    r"C:\Users\Jelil\Desktop\New folder (12)\Pistachio_Image_Dataset\New folder (3)\bestfinal_modelu.pth"
)

train_results = train(
    modelu,
    optimizer2,
    loss_fn,
    train_loader,
    val_loader,
    epochs=epochs_to_train,
    device=device,
    scheduler=scheduler,
    checkpoint_path= checkpoint_path,
    early_stopping=early_stopping,
    )

# create the same architecture
checkpoint = torch.load(
    r"C:\Users\Jelil\Desktop\New folder (12)\Pistachio_Image_Dataset\New folder (3)\best_modelu.pth",
    map_location="cpu"
)

model.load_state_dict(checkpoint["model_state_dict"])

optimizer.load_state_dict(checkpoint["optimizer_state_dict"])

model.eval()

modelu.eval()
with torch.no_grad():
    all_probs = torch.tensor([])
    for images, labels in tqdm(TestLoader, desc = "Testing on unseen data", leave = False):
        pred = modelu(images)
        pred_out1 = torch.nn.functional.softmax(pred, dim = 1)
        all_probs = torch.cat((all_probs, pred_out1),dim = 0)

from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix
import matplotlib.pyplot as plt
targets_val = torch.cat([labels for _, labels in tqdm(TestLoader, desc="Get Labels", leave = False)])

cm = confusion_matrix(targets_val, predictions)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=classes)
# Set figure size

plt.figure(figsize=(10, 8))
disp.plot(cmap=plt.cm.Blues, xticks_rotation="vertical");

predictions = torch.argmax(all_probs, dim = 1)

accuracy = (torch.eq(predictions, targets_val).sum()).item()/len(targets_val)

